// AUTO-GENERATED by Supabase — do not edit manually
// Project: spicy-fairy-tales (kprixebuokkgahohutmn)
// Regenerate: supabase gen types typescript --project-id kprixebuokkgahohutmn

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      arc_summaries: {
        Row: { arc_id: string; chapter_milestone: number; created_at: string; id: string; summary_text: string }
        Insert: { arc_id: string; chapter_milestone: number; created_at?: string; id?: string; summary_text: string }
        Update: { arc_id?: string; chapter_milestone?: number; created_at?: string; id?: string; summary_text?: string }
        Relationships: [{ foreignKeyName: "arc_summaries_arc_id_fkey"; columns: ["arc_id"]; isOneToOne: false; referencedRelation: "arcs"; referencedColumns: ["id"] }]
      }
      arcs: {
        Row: {
          arc_type: string; atmosphere_archetype: string; cover_image_url: string | null
          created_at: string; creature_type: string; default_sense_primary: string
          default_sense_secondary: string; default_spice_level: number; dialogue_ratio_pct: number
          genre_blend_primary: string; genre_blend_ratio: number; genre_blend_secondary: string | null
          hook_density: string; id: string; is_quick_start: boolean; narrative_distance: string
          pacing_rhythm: string; pov_mode: string; reading_level: string; recurring_motif: string | null
          scene_count_default: number; tense: string; themes: string[]; title: string | null
          tone_allowance: string; updated_at: string; user_id: string
        }
        Insert: {
          arc_type?: string; atmosphere_archetype?: string; cover_image_url?: string | null
          created_at?: string; creature_type: string; default_sense_primary?: string
          default_sense_secondary?: string; default_spice_level?: number; dialogue_ratio_pct?: number
          genre_blend_primary?: string; genre_blend_ratio?: number; genre_blend_secondary?: string | null
          hook_density?: string; id?: string; is_quick_start?: boolean; narrative_distance?: string
          pacing_rhythm?: string; pov_mode?: string; reading_level?: string; recurring_motif?: string | null
          scene_count_default?: number; tense?: string; themes?: string[]; title?: string | null
          tone_allowance?: string; updated_at?: string; user_id: string
        }
        Update: Partial<Database['public']['Tables']['arcs']['Insert']>
        Relationships: []
      }
      chapters: {
        Row: {
          arc_id: string; archived_at: string | null; beat_used: string; chapter_number: number
          chekhov_seeded: string[] | null; cliffhanger_type: string; content: string
          dialogue_ratio_pct: number; dropped_modules: string[] | null; emotional_arc: string
          engine_version: string; generated_at: string; generation_attempt: number; id: string
          parent_chapter_id: string | null; spice_level_used: number; status: string
          system_prompt_used: string | null; title: string | null; word_count: number
        }
        Insert: {
          arc_id: string; archived_at?: string | null; beat_used?: string; chapter_number: number
          chekhov_seeded?: string[] | null; cliffhanger_type?: string; content: string
          dialogue_ratio_pct?: number; dropped_modules?: string[] | null; emotional_arc?: string
          engine_version?: string; generated_at?: string; generation_attempt?: number; id?: string
          parent_chapter_id?: string | null; spice_level_used?: number; status?: string
          system_prompt_used?: string | null; title?: string | null; word_count?: number
        }
        Update: Partial<Database['public']['Tables']['chapters']['Insert']>
        Relationships: [
          { foreignKeyName: "chapters_arc_id_fkey"; columns: ["arc_id"]; isOneToOne: false; referencedRelation: "arcs"; referencedColumns: ["id"] },
          { foreignKeyName: "chapters_parent_chapter_id_fkey"; columns: ["parent_chapter_id"]; isOneToOne: false; referencedRelation: "chapters"; referencedColumns: ["id"] }
        ]
      }
      characters: {
        Row: {
          accent_id: string | null; accent_region: string | null; apparent_age: number | null
          appearance: string; arc_id: string; bio: string; created_at: string; display_name: string
          emotion_state_ids: string[] | null; flaw: string | null; hidden_need: string | null; id: string
          is_protagonist: boolean; lie: string | null; slug: string; species: string
          speech_avg_sentence_length: string | null; speech_signature_phrase: string | null
          speech_verbal_tic: string | null; stated_desire: string | null; true_age: number | null
          vocab_register: string; wound: string | null
        }
        Insert: {
          accent_id?: string | null; accent_region?: string | null; apparent_age?: number | null
          appearance?: string; arc_id: string; bio?: string; created_at?: string; display_name: string
          emotion_state_ids?: string[] | null; flaw?: string | null; hidden_need?: string | null; id?: string
          is_protagonist?: boolean; lie?: string | null; slug: string; species?: string
          speech_avg_sentence_length?: string | null; speech_signature_phrase?: string | null
          speech_verbal_tic?: string | null; stated_desire?: string | null; true_age?: number | null
          vocab_register?: string; wound?: string | null
        }
        Update: Partial<Database['public']['Tables']['characters']['Insert']>
        Relationships: [{ foreignKeyName: "characters_arc_id_fkey"; columns: ["arc_id"]; isOneToOne: false; referencedRelation: "arcs"; referencedColumns: ["id"] }]
      }
      creature_lore: {
        Row: { abilities: string[] | null; arc_id: string; creature_type: string; custom_fields: Json | null; id: string; rules: string[] | null; society_notes: string | null; weaknesses: string[] | null }
        Insert: { abilities?: string[] | null; arc_id: string; creature_type: string; custom_fields?: Json | null; id?: string; rules?: string[] | null; society_notes?: string | null; weaknesses?: string[] | null }
        Update: Partial<Database['public']['Tables']['creature_lore']['Insert']>
        Relationships: [{ foreignKeyName: "creature_lore_arc_id_fkey"; columns: ["arc_id"]; isOneToOne: true; referencedRelation: "arcs"; referencedColumns: ["id"] }]
      }
      plot_threads: {
        Row: { arc_id: string; created_at: string; description: string; expected_payoff_chapter: number | null; id: string; planted_in_chapter: number; resolution_note: string | null; resolved_in_chapter: number | null; status: string; thread_type: string }
        Insert: { arc_id: string; created_at?: string; description: string; expected_payoff_chapter?: number | null; id?: string; planted_in_chapter: number; resolution_note?: string | null; resolved_in_chapter?: number | null; status?: string; thread_type?: string }
        Update: Partial<Database['public']['Tables']['plot_threads']['Insert']>
        Relationships: [{ foreignKeyName: "plot_threads_arc_id_fkey"; columns: ["arc_id"]; isOneToOne: false; referencedRelation: "arcs"; referencedColumns: ["id"] }]
      }
      profiles: {
        Row: { created_at: string; id: string; monthly_generation_count: number; monthly_reset_date: string; subscription_tier: string }
        Insert: { created_at?: string; id: string; monthly_generation_count?: number; monthly_reset_date?: string; subscription_tier?: string }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
        Relationships: []
      }
      relationship_map: {
        Row: { arc_id: string; character_a_id: string; character_b_id: string; current_dynamic: string; history: string; id: string; power_holder: string; tension_type: string }
        Insert: { arc_id: string; character_a_id: string; character_b_id: string; current_dynamic?: string; history?: string; id?: string; power_holder?: string; tension_type?: string }
        Update: Partial<Database['public']['Tables']['relationship_map']['Insert']>
        Relationships: [
          { foreignKeyName: "relationship_map_arc_id_fkey"; columns: ["arc_id"]; isOneToOne: false; referencedRelation: "arcs"; referencedColumns: ["id"] },
          { foreignKeyName: "relationship_map_character_a_id_fkey"; columns: ["character_a_id"]; isOneToOne: false; referencedRelation: "characters"; referencedColumns: ["id"] },
          { foreignKeyName: "relationship_map_character_b_id_fkey"; columns: ["character_b_id"]; isOneToOne: false; referencedRelation: "characters"; referencedColumns: ["id"] }
        ]
      }
      world_notes: {
        Row: { arc_id: string; category: string; content: string; created_at: string; id: string; is_active: boolean }
        Insert: { arc_id: string; category?: string; content: string; created_at?: string; id?: string; is_active?: boolean }
        Update: Partial<Database['public']['Tables']['world_notes']['Insert']>
        Relationships: [{ foreignKeyName: "world_notes_arc_id_fkey"; columns: ["arc_id"]; isOneToOne: false; referencedRelation: "arcs"; referencedColumns: ["id"] }]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      increment_generation_count: { Args: { p_limit: number; p_user_id: string }; Returns: boolean }
      owns_arc: { Args: { p_arc: string }; Returns: boolean }
      publish_chapter: { Args: { p_chapter_id: string }; Returns: undefined }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
